"""
ROBOMLM PLUS
Permission Constants
Module: app/core/constants/permission_constants.py

Purpose:
    Centralized permission identifiers used by authorization,
    entitlement, API and UI access-control layers.

    This module defines permissions only.
    Permission evaluation belongs to authorization services.
"""

from __future__ import annotations


# ==================================================
# GENERAL
# ==================================================

PERMISSION_NONE = "NONE"

PERMISSION_READ = "READ"
PERMISSION_WRITE = "WRITE"
PERMISSION_CREATE = "CREATE"
PERMISSION_UPDATE = "UPDATE"
PERMISSION_DELETE = "DELETE"
PERMISSION_EXECUTE = "EXECUTE"


# ==================================================
# ACCOUNT
# ==================================================

PERMISSION_ACCOUNT_VIEW = "ACCOUNT_VIEW"
PERMISSION_ACCOUNT_UPDATE = "ACCOUNT_UPDATE"

PERMISSION_PROFILE_VIEW = "PROFILE_VIEW"
PERMISSION_PROFILE_UPDATE = "PROFILE_UPDATE"

PERMISSION_SECURITY_VIEW = "SECURITY_VIEW"
PERMISSION_SECURITY_UPDATE = "SECURITY_UPDATE"


# ==================================================
# SUBSCRIPTION / BILLING
# ==================================================

PERMISSION_SUBSCRIPTION_VIEW = "SUBSCRIPTION_VIEW"
PERMISSION_SUBSCRIPTION_MANAGE = "SUBSCRIPTION_MANAGE"

PERMISSION_BILLING_VIEW = "BILLING_VIEW"
PERMISSION_BILLING_MANAGE = "BILLING_MANAGE"


# ==================================================
# MARKET ACCESS
# ==================================================

PERMISSION_MARKET_VIEW = "MARKET_VIEW"
PERMISSION_MARKET_DATA = "MARKET_DATA"

PERMISSION_STOCK_ACCESS = "STOCK_ACCESS"
PERMISSION_INDEX_ACCESS = "INDEX_ACCESS"
PERMISSION_FX_ACCESS = "FX_ACCESS"
PERMISSION_CRYPTO_ACCESS = "CRYPTO_ACCESS"
PERMISSION_COMMODITY_ACCESS = "COMMODITY_ACCESS"


# ==================================================
# TERMINAL
# ==================================================

PERMISSION_TERMINAL_VIEW = "TERMINAL_VIEW"

PERMISSION_TERMINAL_ANALYSIS = "TERMINAL_ANALYSIS"

PERMISSION_TERMINAL_DECISION = "TERMINAL_DECISION"

PERMISSION_TERMINAL_EVIDENCE = "TERMINAL_EVIDENCE"

PERMISSION_TERMINAL_RISK = "TERMINAL_RISK"


# ==================================================
# DISCOVERY
# ==================================================

PERMISSION_DISCOVERY_VIEW = "DISCOVERY_VIEW"

PERMISSION_DISCOVERY_SCAN = "DISCOVERY_SCAN"

PERMISSION_DISCOVERY_RANK = "DISCOVERY_RANK"

PERMISSION_DISCOVERY_FAVORITES = "DISCOVERY_FAVORITES"


# ==================================================
# MEMORY
# ==================================================

PERMISSION_MEMORY_VIEW = "MEMORY_VIEW"

PERMISSION_MEMORY_SEARCH = "MEMORY_SEARCH"

PERMISSION_MEMORY_ANALYSIS = "MEMORY_ANALYSIS"


# ==================================================
# RESEARCH
# ==================================================

PERMISSION_RESEARCH_VIEW = "RESEARCH_VIEW"

PERMISSION_RESEARCH_CREATE = "RESEARCH_CREATE"

PERMISSION_RESEARCH_EXPERIMENT = "RESEARCH_EXPERIMENT"

PERMISSION_RESEARCH_VALIDATE = "RESEARCH_VALIDATE"

PERMISSION_RESEARCH_STRESS_TEST = "RESEARCH_STRESS_TEST"

PERMISSION_RESEARCH_VERSION = "RESEARCH_VERSION"


# ==================================================
# BUYER
# ==================================================

PERMISSION_BUYER_VIEW = "BUYER_VIEW"

PERMISSION_BUYER_ANALYSIS = "BUYER_ANALYSIS"

PERMISSION_BUYER_INTELLIGENCE = "BUYER_INTELLIGENCE"

PERMISSION_BUYER_DECISION = "BUYER_DECISION"

PERMISSION_BUYER_RISK = "BUYER_RISK"

PERMISSION_BUYER_STRATEGY = "BUYER_STRATEGY"

PERMISSION_BUYER_CAS = "BUYER_CAS"

PERMISSION_BUYER_PLUS = "BUYER_PLUS"


# ==================================================
# ROBOMLM PLUS
# ==================================================

PERMISSION_PLUS_VIEW = "PLUS_VIEW"

PERMISSION_PLUS_ANALYSIS = "PLUS_ANALYSIS"

PERMISSION_PLUS_EXECUTION_PREPARATION = (
    "PLUS_EXECUTION_PREPARATION"
)

PERMISSION_PLUS_POSITION_MONITOR = "PLUS_POSITION_MONITOR"

PERMISSION_PLUS_PROTECTION = "PLUS_PROTECTION"

PERMISSION_PLUS_RECONCILIATION = "PLUS_RECONCILIATION"

PERMISSION_PLUS_EMERGENCY_CONTROL = "PLUS_EMERGENCY_CONTROL"


# ==================================================
# AUTOMATION
# ==================================================

PERMISSION_AUTOMATION_VIEW = "AUTOMATION_VIEW"

PERMISSION_AUTOMATION_CONFIGURE = "AUTOMATION_CONFIGURE"

PERMISSION_AUTOMATION_START = "AUTOMATION_START"

PERMISSION_AUTOMATION_STOP = "AUTOMATION_STOP"

PERMISSION_AUTOMATION_PAUSE = "AUTOMATION_PAUSE"

PERMISSION_AUTOMATION_EXECUTE = "AUTOMATION_EXECUTE"


# ==================================================
# EXECUTION
# ==================================================

PERMISSION_EXECUTION_VIEW = "EXECUTION_VIEW"

PERMISSION_EXECUTION_PREPARE = "EXECUTION_PREPARE"

PERMISSION_EXECUTION_SUBMIT = "EXECUTION_SUBMIT"

PERMISSION_EXECUTION_CANCEL = "EXECUTION_CANCEL"

PERMISSION_EXECUTION_MANAGE = "EXECUTION_MANAGE"


# ==================================================
# POSITION
# ==================================================

PERMISSION_POSITION_VIEW = "POSITION_VIEW"

PERMISSION_POSITION_MANAGE = "POSITION_MANAGE"

PERMISSION_POSITION_CLOSE = "POSITION_CLOSE"


# ==================================================
# RISK
# ==================================================

PERMISSION_RISK_VIEW = "RISK_VIEW"

PERMISSION_RISK_ANALYSIS = "RISK_ANALYSIS"

PERMISSION_RISK_OVERRIDE = "RISK_OVERRIDE"


# ==================================================
# KILL SWITCH
# ==================================================

PERMISSION_KILL_SWITCH_VIEW = "KILL_SWITCH_VIEW"

PERMISSION_KILL_SWITCH_ACTIVATE = "KILL_SWITCH_ACTIVATE"

PERMISSION_KILL_SWITCH_DEACTIVATE = "KILL_SWITCH_DEACTIVATE"


# ==================================================
# ADMIN
# ==================================================

PERMISSION_ADMIN_VIEW = "ADMIN_VIEW"

PERMISSION_ADMIN_MANAGE = "ADMIN_MANAGE"

PERMISSION_ADMIN_CONFIGURE = "ADMIN_CONFIGURE"


# ==================================================
# ADMIN — DEPLOYMENT
# ==================================================

PERMISSION_DEPLOYMENT_VIEW = "DEPLOYMENT_VIEW"

PERMISSION_DEPLOYMENT_CREATE = "DEPLOYMENT_CREATE"

PERMISSION_DEPLOYMENT_VALIDATE = "DEPLOYMENT_VALIDATE"

PERMISSION_DEPLOYMENT_RELEASE = "DEPLOYMENT_RELEASE"

PERMISSION_DEPLOYMENT_ROLLBACK = "DEPLOYMENT_ROLLBACK"


# ==================================================
# ADMIN — RESEARCH
# ==================================================

PERMISSION_ADMIN_RESEARCH = "ADMIN_RESEARCH"

PERMISSION_ADMIN_EXPERIMENT = "ADMIN_EXPERIMENT"

PERMISSION_ADMIN_VALIDATION = "ADMIN_VALIDATION"

PERMISSION_ADMIN_STRESS_TEST = "ADMIN_STRESS_TEST"


# ==================================================
# ADMIN — VERSION
# ==================================================

PERMISSION_VERSION_VIEW = "VERSION_VIEW"

PERMISSION_VERSION_CREATE = "VERSION_CREATE"

PERMISSION_VERSION_ACTIVATE = "VERSION_ACTIVATE"

PERMISSION_VERSION_ROLLBACK = "VERSION_ROLLBACK"


# ==================================================
# AUDIT / BLACKBOX
# ==================================================

PERMISSION_AUDIT_VIEW = "AUDIT_VIEW"

PERMISSION_AUDIT_EXPORT = "AUDIT_EXPORT"

PERMISSION_BLACKBOX_VIEW = "BLACKBOX_VIEW"

PERMISSION_BLACKBOX_EXPORT = "BLACKBOX_EXPORT"


# ==================================================
# NOTIFICATIONS
# ==================================================

PERMISSION_NOTIFICATION_VIEW = "NOTIFICATION_VIEW"

PERMISSION_NOTIFICATION_MANAGE = "NOTIFICATION_MANAGE"


# ==================================================
# API
# ==================================================

PERMISSION_API_ACCESS = "API_ACCESS"

PERMISSION_WEBSOCKET_ACCESS = "WEBSOCKET_ACCESS"


# ==================================================
# PERMISSION GROUPS
# ==================================================

READ_PERMISSIONS = (
    PERMISSION_READ,
    PERMISSION_ACCOUNT_VIEW,
    PERMISSION_PROFILE_VIEW,
    PERMISSION_SECURITY_VIEW,
    PERMISSION_SUBSCRIPTION_VIEW,
    PERMISSION_BILLING_VIEW,
    PERMISSION_MARKET_VIEW,
    PERMISSION_MARKET_DATA,
    PERMISSION_TERMINAL_VIEW,
    PERMISSION_DISCOVERY_VIEW,
    PERMISSION_MEMORY_VIEW,
    PERMISSION_RESEARCH_VIEW,
    PERMISSION_BUYER_VIEW,
    PERMISSION_PLUS_VIEW,
    PERMISSION_AUTOMATION_VIEW,
    PERMISSION_EXECUTION_VIEW,
    PERMISSION_POSITION_VIEW,
    PERMISSION_RISK_VIEW,
    PERMISSION_ADMIN_VIEW,
    PERMISSION_DEPLOYMENT_VIEW,
    PERMISSION_VERSION_VIEW,
    PERMISSION_AUDIT_VIEW,
    PERMISSION_BLACKBOX_VIEW,
    PERMISSION_NOTIFICATION_VIEW,
)


WRITE_PERMISSIONS = (
    PERMISSION_WRITE,
    PERMISSION_ACCOUNT_UPDATE,
    PERMISSION_PROFILE_UPDATE,
    PERMISSION_SECURITY_UPDATE,
    PERMISSION_SUBSCRIPTION_MANAGE,
    PERMISSION_BILLING_MANAGE,
    PERMISSION_AUTOMATION_CONFIGURE,
    PERMISSION_POSITION_MANAGE,
    PERMISSION_ADMIN_MANAGE,
    PERMISSION_ADMIN_CONFIGURE,
    PERMISSION_NOTIFICATION_MANAGE,
)


EXECUTION_PERMISSIONS = (
    PERMISSION_EXECUTION_PREPARE,
    PERMISSION_EXECUTION_SUBMIT,
    PERMISSION_EXECUTION_CANCEL,
    PERMISSION_EXECUTION_MANAGE,
    PERMISSION_AUTOMATION_EXECUTE,
    PERMISSION_POSITION_CLOSE,
)


ADMIN_PERMISSIONS = (
    PERMISSION_ADMIN_VIEW,
    PERMISSION_ADMIN_MANAGE,
    PERMISSION_ADMIN_CONFIGURE,
    PERMISSION_DEPLOYMENT_VIEW,
    PERMISSION_DEPLOYMENT_CREATE,
    PERMISSION_DEPLOYMENT_VALIDATE,
    PERMISSION_DEPLOYMENT_RELEASE,
    PERMISSION_DEPLOYMENT_ROLLBACK,
    PERMISSION_ADMIN_RESEARCH,
    PERMISSION_ADMIN_EXPERIMENT,
    PERMISSION_ADMIN_VALIDATION,
    PERMISSION_ADMIN_STRESS_TEST,
    PERMISSION_VERSION_VIEW,
    PERMISSION_VERSION_CREATE,
    PERMISSION_VERSION_ACTIVATE,
    PERMISSION_VERSION_ROLLBACK,
)


# ==================================================
# HELPERS
# ==================================================

ALL_PERMISSIONS = tuple(
    dict.fromkeys(
        READ_PERMISSIONS
        + WRITE_PERMISSIONS
        + EXECUTION_PERMISSIONS
        + ADMIN_PERMISSIONS
    )
)


def is_known_permission(permission: str) -> bool:
    """Return True when the permission is registered here."""
    return permission in ALL_PERMISSIONS