"""
ROBOMLM PLUS
Status Constants
Module: app/core/constants/status_constants.py

Purpose:
    Centralized status identifiers used across ROBOMLM PLUS.

    This module defines status vocabulary only.
    State transitions and business rules belong to their respective
    services, engines and orchestrators.
"""

from __future__ import annotations


# ============================================================
# GENERIC SYSTEM STATUS
# ============================================================

STATUS_UNKNOWN = "UNKNOWN"
STATUS_INITIALIZING = "INITIALIZING"
STATUS_STARTING = "STARTING"
STATUS_READY = "READY"
STATUS_RUNNING = "RUNNING"
STATUS_PROCESSING = "PROCESSING"
STATUS_ACTIVE = "ACTIVE"
STATUS_INACTIVE = "INACTIVE"
STATUS_PAUSED = "PAUSED"
STATUS_STOPPED = "STOPPED"
STATUS_COMPLETED = "COMPLETED"
STATUS_FAILED = "FAILED"
STATUS_ERROR = "ERROR"
STATUS_WARNING = "WARNING"
STATUS_DISABLED = "DISABLED"
STATUS_ENABLED = "ENABLED"
STATUS_PENDING = "PENDING"
STATUS_REJECTED = "REJECTED"
STATUS_CANCELLED = "CANCELLED"


# ============================================================
# APPLICATION STATUS
# ============================================================

APP_STATUS_INITIALIZING = "APP_INITIALIZING"
APP_STATUS_READY = "APP_READY"
APP_STATUS_RUNNING = "APP_RUNNING"
APP_STATUS_DEGRADED = "APP_DEGRADED"
APP_STATUS_STOPPING = "APP_STOPPING"
APP_STATUS_STOPPED = "APP_STOPPED"
APP_STATUS_FAILED = "APP_FAILED"


# ============================================================
# SERVICE STATUS
# ============================================================

SERVICE_INITIALIZING = "SERVICE_INITIALIZING"
SERVICE_READY = "SERVICE_READY"
SERVICE_RUNNING = "SERVICE_RUNNING"
SERVICE_DEGRADED = "SERVICE_DEGRADED"
SERVICE_STOPPING = "SERVICE_STOPPING"
SERVICE_STOPPED = "SERVICE_STOPPED"
SERVICE_FAILED = "SERVICE_FAILED"


# ============================================================
# HEALTH STATUS
# ============================================================

HEALTH_UNKNOWN = "HEALTH_UNKNOWN"
HEALTH_HEALTHY = "HEALTHY"
HEALTH_DEGRADED = "DEGRADED"
HEALTH_UNHEALTHY = "UNHEALTHY"
HEALTH_OFFLINE = "OFFLINE"


# ============================================================
# CONNECTION STATUS
# ============================================================

CONNECTION_UNKNOWN = "CONNECTION_UNKNOWN"
CONNECTION_CONNECTING = "CONNECTING"
CONNECTION_CONNECTED = "CONNECTED"
CONNECTION_RECONNECTING = "RECONNECTING"
CONNECTION_DISCONNECTED = "DISCONNECTED"
CONNECTION_FAILED = "CONNECTION_FAILED"


# ============================================================
# AUTHENTICATION STATUS
# ============================================================

AUTH_UNKNOWN = "AUTH_UNKNOWN"
AUTH_PENDING = "AUTH_PENDING"
AUTHENTICATED = "AUTHENTICATED"
AUTH_UNAUTHENTICATED = "UNAUTHENTICATED"
AUTH_EXPIRED = "AUTH_EXPIRED"
AUTH_REVOKED = "AUTH_REVOKED"
AUTH_FAILED = "AUTH_FAILED"
AUTH_LOCKED = "AUTH_LOCKED"


# ============================================================
# USER ACCOUNT STATUS
# ============================================================

USER_PENDING = "USER_PENDING"
USER_ACTIVE = "USER_ACTIVE"
USER_INACTIVE = "USER_INACTIVE"
USER_SUSPENDED = "USER_SUSPENDED"
USER_LOCKED = "USER_LOCKED"
USER_DELETED = "USER_DELETED"


# ============================================================
# SUBSCRIPTION STATUS
# ============================================================

SUBSCRIPTION_PENDING = "SUBSCRIPTION_PENDING"
SUBSCRIPTION_ACTIVE = "SUBSCRIPTION_ACTIVE"
SUBSCRIPTION_TRIAL = "SUBSCRIPTION_TRIAL"
SUBSCRIPTION_PAST_DUE = "SUBSCRIPTION_PAST_DUE"
SUBSCRIPTION_PAUSED = "SUBSCRIPTION_PAUSED"
SUBSCRIPTION_CANCELLED = "SUBSCRIPTION_CANCELLED"
SUBSCRIPTION_EXPIRED = "SUBSCRIPTION_EXPIRED"
SUBSCRIPTION_SUSPENDED = "SUBSCRIPTION_SUSPENDED"


# ============================================================
# ENTITLEMENT STATUS
# ============================================================

ENTITLEMENT_UNKNOWN = "ENTITLEMENT_UNKNOWN"
ENTITLEMENT_AVAILABLE = "ENTITLEMENT_AVAILABLE"
ENTITLEMENT_GRANTED = "ENTITLEMENT_GRANTED"
ENTITLEMENT_DENIED = "ENTITLEMENT_DENIED"
ENTITLEMENT_EXPIRED = "ENTITLEMENT_EXPIRED"
ENTITLEMENT_REVOKED = "ENTITLEMENT_REVOKED"


# ============================================================
# MARKET STATUS
# ============================================================

MARKET_UNKNOWN = "MARKET_UNKNOWN"
MARKET_PRE_OPEN = "PRE_OPEN"
MARKET_OPEN = "OPEN"
MARKET_CLOSED = "CLOSED"
MARKET_HOLIDAY = "HOLIDAY"
MARKET_HALTED = "HALTED"
MARKET_SUSPENDED = "SUSPENDED"
MARKET_CLOSING = "CLOSING"


# ============================================================
# MARKET DATA STATUS
# ============================================================

DATA_UNKNOWN = "DATA_UNKNOWN"
DATA_INITIALIZING = "DATA_INITIALIZING"
DATA_AVAILABLE = "DATA_AVAILABLE"
DATA_FRESH = "DATA_FRESH"
DATA_STALE = "DATA_STALE"
DATA_DELAYED = "DATA_DELAYED"
DATA_INCOMPLETE = "DATA_INCOMPLETE"
DATA_INVALID = "DATA_INVALID"
DATA_UNAVAILABLE = "DATA_UNAVAILABLE"
DATA_DISCONNECTED = "DATA_DISCONNECTED"


# ============================================================
# DATA QUALITY STATUS
# ============================================================

QUALITY_UNKNOWN = "QUALITY_UNKNOWN"
QUALITY_EXCELLENT = "QUALITY_EXCELLENT"
QUALITY_GOOD = "QUALITY_GOOD"
QUALITY_ACCEPTABLE = "QUALITY_ACCEPTABLE"
QUALITY_DEGRADED = "QUALITY_DEGRADED"
QUALITY_POOR = "QUALITY_POOR"
QUALITY_FAILED = "QUALITY_FAILED"


# ============================================================
# EVIDENCE STATUS
# ============================================================

EVIDENCE_UNKNOWN = "EVIDENCE_UNKNOWN"
EVIDENCE_PENDING = "EVIDENCE_PENDING"
EVIDENCE_AVAILABLE = "EVIDENCE_AVAILABLE"
EVIDENCE_VALID = "EVIDENCE_VALID"
EVIDENCE_INVALID = "EVIDENCE_INVALID"
EVIDENCE_CONFLICTED = "EVIDENCE_CONFLICTED"
EVIDENCE_INSUFFICIENT = "EVIDENCE_INSUFFICIENT"
EVIDENCE_STALE = "EVIDENCE_STALE"
EVIDENCE_REJECTED = "EVIDENCE_REJECTED"


# ============================================================
# INTELLIGENCE STATUS
# ============================================================

INTELLIGENCE_UNKNOWN = "INTELLIGENCE_UNKNOWN"
INTELLIGENCE_INITIALIZING = "INTELLIGENCE_INITIALIZING"
INTELLIGENCE_PROCESSING = "INTELLIGENCE_PROCESSING"
INTELLIGENCE_READY = "INTELLIGENCE_READY"
INTELLIGENCE_ACTIVE = "INTELLIGENCE_ACTIVE"
INTELLIGENCE_DEGRADED = "INTELLIGENCE_DEGRADED"
INTELLIGENCE_INSUFFICIENT = "INTELLIGENCE_INSUFFICIENT"
INTELLIGENCE_FAILED = "INTELLIGENCE_FAILED"


# ============================================================
# DECISION STATUS
# ============================================================

DECISION_UNKNOWN = "DECISION_UNKNOWN"
DECISION_PENDING = "DECISION_PENDING"
DECISION_FORMING = "DECISION_FORMING"
DECISION_READY = "DECISION_READY"
DECISION_ACTIONABLE = "DECISION_ACTIONABLE"
DECISION_BLOCKED = "DECISION_BLOCKED"
DECISION_REJECTED = "DECISION_REJECTED"
DECISION_EXPIRED = "DECISION_EXPIRED"
DECISION_SUPERSEDED = "DECISION_SUPERSEDED"
DECISION_EXECUTED = "DECISION_EXECUTED"
DECISION_COMPLETED = "DECISION_COMPLETED"


# ============================================================
# OPPORTUNITY STATUS
# ============================================================

OPPORTUNITY_UNKNOWN = "OPPORTUNITY_UNKNOWN"
OPPORTUNITY_DISCOVERED = "OPPORTUNITY_DISCOVERED"
OPPORTUNITY_ANALYZING = "OPPORTUNITY_ANALYZING"
OPPORTUNITY_QUALIFIED = "OPPORTUNITY_QUALIFIED"
OPPORTUNITY_RANKED = "OPPORTUNITY_RANKED"
OPPORTUNITY_ACTIONABLE = "OPPORTUNITY_ACTIONABLE"
OPPORTUNITY_BLOCKED = "OPPORTUNITY_BLOCKED"
OPPORTUNITY_EXPIRED = "OPPORTUNITY_EXPIRED"
OPPORTUNITY_REJECTED = "OPPORTUNITY_REJECTED"


# ============================================================
# RISK STATUS
# ============================================================

RISK_UNKNOWN = "RISK_UNKNOWN"
RISK_PENDING = "RISK_PENDING"
RISK_ACCEPTABLE = "RISK_ACCEPTABLE"
RISK_ELEVATED = "RISK_ELEVATED"
RISK_HIGH = "RISK_HIGH"
RISK_CRITICAL = "RISK_CRITICAL"
RISK_BLOCKED = "RISK_BLOCKED"
RISK_REJECTED = "RISK_REJECTED"


# ============================================================
# CAS STATUS
# ============================================================

CAS_UNKNOWN = "CAS_UNKNOWN"
CAS_PENDING = "CAS_PENDING"
CAS_EVALUATING = "CAS_EVALUATING"
CAS_PASSED = "CAS_PASSED"
CAS_FAILED = "CAS_FAILED"
CAS_BLOCKED = "CAS_BLOCKED"
CAS_RESTRICTED = "CAS_RESTRICTED"
CAS_EXPIRED = "CAS_EXPIRED"


# ============================================================
# EXECUTION STATUS
# ============================================================

EXECUTION_UNKNOWN = "EXECUTION_UNKNOWN"
EXECUTION_PENDING = "EXECUTION_PENDING"
EXECUTION_PREPARING = "EXECUTION_PREPARING"
EXECUTION_AUTHORIZED = "EXECUTION_AUTHORIZED"
EXECUTION_SUBMITTED = "EXECUTION_SUBMITTED"
EXECUTION_ACCEPTED = "EXECUTION_ACCEPTED"
EXECUTION_REJECTED = "EXECUTION_REJECTED"
EXECUTION_PARTIAL = "EXECUTION_PARTIAL"
EXECUTION_FILLED = "EXECUTION_FILLED"
EXECUTION_CANCEL_PENDING = "EXECUTION_CANCEL_PENDING"
EXECUTION_CANCELLED = "EXECUTION_CANCELLED"
EXECUTION_FAILED = "EXECUTION_FAILED"


# ============================================================
# ORDER STATUS
# ============================================================

ORDER_UNKNOWN = "ORDER_UNKNOWN"
ORDER_PENDING = "ORDER_PENDING"
ORDER_NEW = "ORDER_NEW"
ORDER_ACCEPTED = "ORDER_ACCEPTED"
ORDER_REJECTED = "ORDER_REJECTED"
ORDER_PARTIALLY_FILLED = "ORDER_PARTIALLY_FILLED"
ORDER_FILLED = "ORDER_FILLED"
ORDER_CANCEL_PENDING = "ORDER_CANCEL_PENDING"
ORDER_CANCELLED = "ORDER_CANCELLED"
ORDER_EXPIRED = "ORDER_EXPIRED"
ORDER_FAILED = "ORDER_FAILED"


# ============================================================
# POSITION STATUS
# ============================================================

POSITION_UNKNOWN = "POSITION_UNKNOWN"
POSITION_PENDING = "POSITION_PENDING"
POSITION_OPENING = "POSITION_OPENING"
POSITION_OPEN = "POSITION_OPEN"
POSITION_REDUCING = "POSITION_REDUCING"
POSITION_CLOSING = "POSITION_CLOSING"
POSITION_CLOSED = "POSITION_CLOSED"
POSITION_RECONCILING = "POSITION_RECONCILING"
POSITION_ERROR = "POSITION_ERROR"


# ============================================================
# AUTOMATION STATUS
# ============================================================

AUTOMATION_UNKNOWN = "AUTOMATION_UNKNOWN"
AUTOMATION_DISABLED = "AUTOMATION_DISABLED"
AUTOMATION_READY = "AUTOMATION_READY"
AUTOMATION_ARMED = "AUTOMATION_ARMED"
AUTOMATION_RUNNING = "AUTOMATION_RUNNING"
AUTOMATION_PAUSED = "AUTOMATION_PAUSED"
AUTOMATION_STOPPING = "AUTOMATION_STOPPING"
AUTOMATION_STOPPED = "AUTOMATION_STOPPED"
AUTOMATION_BLOCKED = "AUTOMATION_BLOCKED"
AUTOMATION_FAILED = "AUTOMATION_FAILED"


# ============================================================
# KILL SWITCH STATUS
# ============================================================

KILL_SWITCH_INACTIVE = "KILL_SWITCH_INACTIVE"
KILL_SWITCH_ARMED = "KILL_SWITCH_ARMED"
KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE"
KILL_SWITCH_TRIGGERED = "KILL_SWITCH_TRIGGERED"
KILL_SWITCH_RESET_PENDING = "KILL_SWITCH_RESET_PENDING"


# ============================================================
# RESEARCH STATUS
# ============================================================

RESEARCH_UNKNOWN = "RESEARCH_UNKNOWN"
RESEARCH_DRAFT = "RESEARCH_DRAFT"
RESEARCH_ACTIVE = "RESEARCH_ACTIVE"
RESEARCH_RUNNING = "RESEARCH_RUNNING"
RESEARCH_PAUSED = "RESEARCH_PAUSED"
RESEARCH_COMPLETED = "RESEARCH_COMPLETED"
RESEARCH_FAILED = "RESEARCH_FAILED"
RESEARCH_ARCHIVED = "RESEARCH_ARCHIVED"


# ============================================================
# EXPERIMENT STATUS
# ============================================================

EXPERIMENT_UNKNOWN = "EXPERIMENT_UNKNOWN"
EXPERIMENT_DRAFT = "EXPERIMENT_DRAFT"
EXPERIMENT_READY = "EXPERIMENT_READY"
EXPERIMENT_RUNNING = "EXPERIMENT_RUNNING"
EXPERIMENT_PAUSED = "EXPERIMENT_PAUSED"
EXPERIMENT_COMPLETED = "EXPERIMENT_COMPLETED"
EXPERIMENT_FAILED = "EXPERIMENT_FAILED"
EXPERIMENT_ABORTED = "EXPERIMENT_ABORTED"


# ============================================================
# VALIDATION STATUS
# ============================================================

VALIDATION_UNKNOWN = "VALIDATION_UNKNOWN"
VALIDATION_PENDING = "VALIDATION_PENDING"
VALIDATION_RUNNING = "VALIDATION_RUNNING"
VALIDATION_PASSED = "VALIDATION_PASSED"
VALIDATION_FAILED = "VALIDATION_FAILED"
VALIDATION_BLOCKED = "VALIDATION_BLOCKED"
VALIDATION_EXPIRED = "VALIDATION_EXPIRED"


# ============================================================
# DEPLOYMENT STATUS
# ============================================================

DEPLOYMENT_UNKNOWN = "DEPLOYMENT_UNKNOWN"
DEPLOYMENT_DRAFT = "DEPLOYMENT_DRAFT"
DEPLOYMENT_READY = "DEPLOYMENT_READY"
DEPLOYMENT_VALIDATING = "DEPLOYMENT_VALIDATING"
DEPLOYMENT_APPROVED = "DEPLOYMENT_APPROVED"
DEPLOYMENT_ACTIVE = "DEPLOYMENT_ACTIVE"
DEPLOYMENT_PAUSED = "DEPLOYMENT_PAUSED"
DEPLOYMENT_ROLLED_BACK = "DEPLOYMENT_ROLLED_BACK"
DEPLOYMENT_FAILED = "DEPLOYMENT_FAILED"


# ============================================================
# VERSION STATUS
# ============================================================

VERSION_UNKNOWN = "VERSION_UNKNOWN"
VERSION_DRAFT = "VERSION_DRAFT"
VERSION_VALIDATING = "VERSION_VALIDATING"
VERSION_VALIDATED = "VERSION_VALIDATED"
VERSION_APPROVED = "VERSION_APPROVED"
VERSION_ACTIVE = "VERSION_ACTIVE"
VERSION_DEPRECATED = "VERSION_DEPRECATED"
VERSION_ROLLED_BACK = "VERSION_ROLLED_BACK"
VERSION_ARCHIVED = "VERSION_ARCHIVED"


# ============================================================
# MEMORY STATUS
# ============================================================

MEMORY_UNKNOWN = "MEMORY_UNKNOWN"
MEMORY_AVAILABLE = "MEMORY_AVAILABLE"
MEMORY_RETRIEVING = "MEMORY_RETRIEVING"
MEMORY_RETRIEVED = "MEMORY_RETRIEVED"
MEMORY_STORED = "MEMORY_STORED"
MEMORY_INVALID = "MEMORY_INVALID"
MEMORY_EXPIRED = "MEMORY_EXPIRED"


# ============================================================
# AUDIT / BLACKBOX STATUS
# ============================================================

AUDIT_UNKNOWN = "AUDIT_UNKNOWN"
AUDIT_PENDING = "AUDIT_PENDING"
AUDIT_RECORDED = "AUDIT_RECORDED"
AUDIT_VALID = "AUDIT_VALID"
AUDIT_INVALID = "AUDIT_INVALID"
AUDIT_FAILED = "AUDIT_FAILED"

BLACKBOX_UNKNOWN = "BLACKBOX_UNKNOWN"
BLACKBOX_READY = "BLACKBOX_READY"
BLACKBOX_RECORDING = "BLACKBOX_RECORDING"
BLACKBOX_STOPPED = "BLACKBOX_STOPPED"
BLACKBOX_ERROR = "BLACKBOX_ERROR"


# ============================================================
# HELPER GROUPS
# ============================================================

ACTIVE_STATUSES = (
    STATUS_ACTIVE,
    STATUS_RUNNING,
    STATUS_PROCESSING,
    STATUS_READY,
    APP_STATUS_RUNNING,
    SERVICE_RUNNING,
    INTELLIGENCE_ACTIVE,
    AUTOMATION_RUNNING,
    POSITION_OPEN,
    MARKET_OPEN,
)

TERMINAL_STATUSES = (
    STATUS_COMPLETED,
    STATUS_FAILED,
    STATUS_ERROR,
    STATUS_CANCELLED,
    STATUS_REJECTED,
    STATUS_STOPPED,
    STATUS_DISABLED,
)

FAILURE_STATUSES = (
    STATUS_FAILED,
    STATUS_ERROR,
    APP_STATUS_FAILED,
    SERVICE_FAILED,
    AUTH_FAILED,
    DATA_INVALID,
    QUALITY_FAILED,
    INTELLIGENCE_FAILED,
    EXECUTION_FAILED,
    ORDER_FAILED,
    POSITION_ERROR,
    AUTOMATION_FAILED,
    RESEARCH_FAILED,
    EXPERIMENT_FAILED,
    VALIDATION_FAILED,
    DEPLOYMENT_FAILED,
)

SUCCESS_STATUSES = (
    STATUS_READY,
    STATUS_ACTIVE,
    STATUS_RUNNING,
    STATUS_COMPLETED,
    EVIDENCE_VALID,
    DECISION_READY,
    DECISION_ACTIONABLE,
    CAS_PASSED,
    EXECUTION_ACCEPTED,
    EXECUTION_FILLED,
    ORDER_ACCEPTED,
    ORDER_FILLED,
    VALIDATION_PASSED,
    DEPLOYMENT_APPROVED,
    DEPLOYMENT_ACTIVE,
)


# ============================================================
# HELPERS
# ============================================================

def is_failure_status(status: str) -> bool:
    """Return True when the status represents a failure condition."""
    return status in FAILURE_STATUSES


def is_success_status(status: str) -> bool:
    """Return True when the status represents a successful condition."""
    return status in SUCCESS_STATUSES


def is_terminal_status(status: str) -> bool:
    """Return True when the status represents a terminal state."""
    return status in TERMINAL_STATUSES


def is_active_status(status: str) -> bool:
    """Return True when the status represents an active state."""
    return status in ACTIVE_STATUSES